/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FdAddButton: typeof import('./src/components/fd-add-button')['default']
    FdCascader: typeof import('./src/components/fd-cascader')['default']
    FdDeleteButton: typeof import('./src/components/fd-delete-button')['default']
    FdDialog: typeof import('./src/components/fd-dialog/index.vue')['default']
    FdExport: typeof import('./src/components/fd-export/index.vue')['default']
    FdGrid: typeof import('./src/components/fd-grid/index.vue')['default']
    FdGridItem: typeof import('./src/components/fd-grid-item/index.vue')['default']
    FdImport: typeof import('./src/components/fd-import/index.vue')['default']
    FdOption: typeof import('./src/components/fd-option/index.vue')['default']
    FdSearch: typeof import('./src/components/fd-search/index.vue')['default']
    FdSelect: typeof import('./src/components/fd-select/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const FdAddButton: typeof import('./src/components/fd-add-button')['default']
  const FdCascader: typeof import('./src/components/fd-cascader')['default']
  const FdDeleteButton: typeof import('./src/components/fd-delete-button')['default']
  const FdDialog: typeof import('./src/components/fd-dialog/index.vue')['default']
  const FdExport: typeof import('./src/components/fd-export/index.vue')['default']
  const FdGrid: typeof import('./src/components/fd-grid/index.vue')['default']
  const FdGridItem: typeof import('./src/components/fd-grid-item/index.vue')['default']
  const FdImport: typeof import('./src/components/fd-import/index.vue')['default']
  const FdOption: typeof import('./src/components/fd-option/index.vue')['default']
  const FdSearch: typeof import('./src/components/fd-search/index.vue')['default']
  const FdSelect: typeof import('./src/components/fd-select/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}
