/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FdAddButton: typeof import('./src/components/fd-add-button/index.vue')['default']
    FdCascader: typeof import('./src/components/fd-cascader/index.vue')['default']
    FdCrud: typeof import('./src/components/fd-crud/index')['default']
    FdDeleteButton: typeof import('./src/components/fd-delete-button/index.vue')['default']
    FdDetail: typeof import('./src/components/fd-detail/index.vue')['default']
    FdDialog: typeof import('./src/components/fd-dialog/index.vue')['default']
    FdExport: typeof import('./src/components/fd-export/index.vue')['default']
    FdForm: typeof import('./src/components/fd-form/index.tsx')['default']
    FdGrid: typeof import('./src/components/fd-grid/index.vue')['default']
    FdGridItem: typeof import('./src/components/fd-grid-item/index.vue')['default']
    FdImport: typeof import('./src/components/fd-import/index.vue')['default']
    FdOption: typeof import('./src/components/fd-option/index.vue')['default']
    FdSearch: typeof import('./src/components/fd-search/index.vue')['default']
    FdSelect: typeof import('./src/components/fd-select/index.vue')['default']
    FdTable: typeof import('./src/components/fd-table/index.vue')['default']
    FdUpsert: typeof import('./src/components/fd-upsert/index.vue')['default']
    IconTablerDragDrop: typeof import('~icons/tabler/drag-drop')['default']
    IconTablerHelp: typeof import('~icons/tabler/help')['default']
    IconTablerPin: typeof import('~icons/tabler/pin')['default']
    IconTablerPinFilled: typeof import('~icons/tabler/pin-filled')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const FdAddButton: typeof import('./src/components/fd-add-button/index.vue')['default']
  const FdCascader: typeof import('./src/components/fd-cascader/index.vue')['default']
  const FdCrud: typeof import('./src/components/fd-crud/index')['default']
  const FdDeleteButton: typeof import('./src/components/fd-delete-button/index.vue')['default']
  const FdDetail: typeof import('./src/components/fd-detail/index.vue')['default']
  const FdDialog: typeof import('./src/components/fd-dialog/index.vue')['default']
  const FdExport: typeof import('./src/components/fd-export/index.vue')['default']
  const FdForm: typeof import('./src/components/fd-form/index.tsx')['default']
  const FdGrid: typeof import('./src/components/fd-grid/index.vue')['default']
  const FdGridItem: typeof import('./src/components/fd-grid-item/index.vue')['default']
  const FdImport: typeof import('./src/components/fd-import/index.vue')['default']
  const FdOption: typeof import('./src/components/fd-option/index.vue')['default']
  const FdSearch: typeof import('./src/components/fd-search/index.vue')['default']
  const FdSelect: typeof import('./src/components/fd-select/index.vue')['default']
  const FdTable: typeof import('./src/components/fd-table/index.vue')['default']
  const FdUpsert: typeof import('./src/components/fd-upsert/index.vue')['default']
  const IconTablerDragDrop: typeof import('~icons/tabler/drag-drop')['default']
  const IconTablerHelp: typeof import('~icons/tabler/help')['default']
  const IconTablerPin: typeof import('~icons/tabler/pin')['default']
  const IconTablerPinFilled: typeof import('~icons/tabler/pin-filled')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}