packages:
  - docs
  - examples

catalog:
  '@antfu/ni': ^27.0.1
  '@antfu/utils': ^9.3.0
  '@element-plus/icons-vue': ^2.3.2
  '@fonds/eslint-config': ^1.0.17
  '@fonds/utils': ^1.0.6
  '@types/lodash-es': ^4.17.12
  '@types/node': ^24.10.0
  '@vitejs/plugin-vue': ^6.0.2
  '@vitejs/plugin-vue-jsx': ^5.1.2
  '@vue/test-utils': ^2.4.6
  bumpp: ^10.3.1
  element-plus: ^2.11.8
  eslint: ^9.39.1
  eslint-plugin-format: ^1.0.2
  happy-dom: ^20.0.10
  lint-staged: ^16.2.6
  lodash-es: ^4.17.21
  sass: ^1.94.1
  simple-git-hooks: ^2.13.1
  tinyexec: ^1.0.2
  tsx: ^4.20.6
  typescript: ^5.9.3
  uuid: ^13.0.0
  vite: ^7.2.1
  vite-plugin-dts: ^4.5.4
  vitepress: ^1.6.4
  vitest: ^4.0.7
  vitest-package-exports: ^0.1.1
  vue: ^3.5.24
  vue-router: ^4.6.3
  vue-tsc: ^3.1.4
  yaml: ^2.8.1

ignoreWorkspaceRootCheck: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - vue-demi

shellEmulator: true
