export * from "../components/fd-detail/type"
export * from "../components/fd-form/type"
export * from "../components/fd-table/type"
export * from "./config"
export * from "./crud"
export * from "./search"
